-- Kör: podman exec -i postgres psql -U recipes -d recipes < docker-dev/seed.sql

INSERT INTO recipes (name, description, steps, servings, cook_time_minutes) VALUES
('Pasta Carbonara', 'Klassisk romersk pasta med ägg, pecorino och guanciale.', '["Koka pasta al dente","Stek guanciale krispigt","Blanda ägg och riven pecorino","Vänd ner pasta och stek, tillsätt äggblandningen off heat","Salta och peppra rikligt"]', 4, 25),
('Köttbullar med gräddsås', 'Svenska köttbullar med krämig gräddsås och lingonsylt.', '["Blanda köttfärs, ägg, lök och kryddor","Rulla till bollar","Stek i smör tills gyllenbruna","Gör gräddsåsen i stekpannan","Servera med potatismos och lingon"]', 4, 40),
('Kycklingwok med grönsaker', 'Snabb och smarrig wok med kyckling och säsongens grönsaker.', '["Skär kyckling i bitar","Hacka grönsaker","Hetta upp woken tills rykande het","Woka kyckling, tillsätt grönsaker","Smaksätt med soja och ingefära"]', 3, 20),
('Lax med dillsås', 'Ugnsbakad lax med klassisk svensk dillsås och kokt potatis.', '["Lägg laxen i ugnsform","Salta och peppra","Baka i 180°C i 15 min","Koka potatis","Blanda dillsås av gräddfil, dill och citron"]', 4, 30),
('Pannkakor', 'Tunna svenska pannkakor serverade med sylt och grädde.', '["Blanda mjöl och mjölk till slät smet","Tillsätt ägg och en nypa salt","Låt vila 30 min","Stek tunna pannkakor i smör","Servera med jordgubbssylt och vispgrädde"]', 4, 45),
('Tacos', 'Mexikanska tacos med kryddad köttfärs och tillbehör.', '["Stek köttfärs med lök","Tillsätt taco-kryddor och vatten","Låt puttra","Värm tortillabröd","Servera med salsa, guacamole, sallad och ost"]', 4, 30),
('Vegetarisk lasagne', 'Mustig lasagne med ricotta, spenat och tomatsås.', '["Stek lök och vitlök","Tillsätt krossade tomater och spenat","Blanda ricotta med ägg och parmesan","Varva sås, lasagneplattor och ricotta","Baka i 200°C i 40 min"]', 6, 80),
('Ceviche', 'Fräsch peruansk ceviche med vitfisk, lime och chili.', '["Skär fisk i bitar","Marinera i pressad lime 15 min","Tillsätt hackad chili och rödlök","Blanda med koriander","Servera direkt med majschips"]', 2, 20),
('Hummus', 'Hemgjord hummus på kikärtor med citron och tahini.', '["Koka kikärtor mjuka","Mixa med tahini, citronsaft och vitlök","Späd med olivolja och lite vatten","Smaksätt med salt och spiskummin","Garnera med paprikapulver och olivolja"]', 6, 15),
('Risotto ai funghi', 'Krämig svamprisotto med parmesan och vitt vin.', '["Stek schalottenlök i smör","Tillsätt arborio-ris och rosta","Häll i vitt vin under omrörning","Tillsätt varm buljong skopa för skopa","Rör i smör, parmesan och stekta svampar"]', 4, 35),
('Falafelbröd', 'Hemgjorda falafel i pitabröd med tahini och grönsaker.', '["Blötlägg kikärtor natten innan","Mixa med lök, koriander och kryddor","Forma bollar","Fritera i het olja","Servera i pitabröd med tahini, sallad och tomater"]', 4, 45),
('Tomatsoppa med basilika', 'Enkel och god tomatsoppa gjord på konserverade tomater.', '["Stek lök och vitlök i olivolja","Tillsätt krossade tomater och buljong","Låt puttra 20 min","Mixa slät med stavmixer","Smaksätt och servera med basilika och bröd"]', 4, 30),
('Biff Stroganoff', 'Klassisk rysk rätt med biff, svamp och grädde.', '["Skär biff i strimlor","Stek svamp och lök","Stek biffsremsor snabbt på hög värme","Blanda ihop med grädde och tomatpuré","Servera med pasta eller ris"]', 4, 35),
('Grekisk sallad', 'Fräsch sallad med tomat, gurka, fetaost och oliver.', '["Skär tomat och gurka i bitar","Dela oliver och rödlök","Smula fetaost över salladen","Ringla olivolja och lite vinäger","Strö oregano och smaksätt"]', 2, 10),
('Tikka Masala', 'Krämig indisk kycklingrätt i tomatsås med yoghurt.', '["Marinera kyckling i yoghurt och kryddor","Stek kycklingen","Tillsätt lök, ingefära och vitlök","Häll i krossade tomater och grädde","Låt puttra och servera med naan"]', 4, 50),
('Äggröra med lax', 'Len äggröra toppat med gravlax och gräslök.', '["Vispa ägg med lite mjölk","Stek i smör på låg värme under ständig omrörning","Ta av innan helt stelnat","Toppa med gravlax","Strö gräslök och servera på rostat bröd"]', 2, 10),
('Moussaka', 'Traditionell grekisk moussaka med aubergine och lammfärs.', '["Skiva och salta aubergine, låt rinna av","Stek aubergine i olja","Gör köttfärssås med lamm och tomater","Gör bechamelsås","Varva och baka i 180°C i 45 min"]', 6, 90),
('Sommarsoppa', 'Len svensk sommarsoppa med nylök, morötter och grädde.', '["Stek nylök i smör","Tillsätt tärnade morötter och potatis","Häll på hönsbuljong","Låt koka tills grönsakerna är mjuka","Tillsätt grädde och smaksätt med dill"]', 4, 30),
('Pulled Pork Bao', 'Ångade baobröd med slow-cooked pulled pork och picklade grönsaker.', '["Gnid in fläskköttet med kryddor","Baka i 120°C i 6 timmar","Dra isär köttet","Ångkoka baobröden","Fyll med kött, picklad gurka och sriracha-majonnäs"]', 4, 380),
('Chokladmousse', 'Luftig och rik chokladmousse på mörk choklad.', '["Smält mörk choklad i vattenbad","Vispa äggulor med socker tills vitt och pösigt","Vänd ner chokladen","Vispa grädde till mjuka toppar","Vänd försiktigt ihop och kyl 2 timmar"]', 6, 30);
